#Requires -Version 5.1
<#
.SYNOPSIS
    Generate cockpit daily report v0.1 (M2.2, Phase B-α、検診プロトコル v0.2 §8-A 物理装置)

.DESCRIPTION
    三者統合判断レポート v0.2(daily_report_20260430_v0_2.md)の自動生成版。
    09:00 JST 三者検診時に daily_cockpit_{YYYYMMDD}.md 自動出力。

    入力源:
    - sync/cockpit_state/pipeline_state.json (M2.4 sync-schtasks-state.ps1 出力)
    - archive/error_patterns.md (EVT 累積)
    - archive/board_council_decisions.md (B-番号台帳)
    - outbox/ (発令累積)
    - sync/checkup-scores/role_execution/ (役割実行スコア)

    出力:
    - 02_physical/cockpit/daily_cockpit_{YYYYMMDD}.md

    検診プロトコル v0.2 §8 統合:
    - §8-A 自動生成
    - §8-B アラート発火(critical / warning / info)
    - §8-C 月次トレンド分析(将来 M3.7 で実装)

.PARAMETER DryRun
    レポート生成のみ、ファイル書込なし

.NOTES
    Drafted: 2026-04-30 (Day 132 evening, supervisor instance A = Argus)
    Basis:
    - M2.2 段階 2 P1 マイルストーン
    - 検診プロトコル v0.2 §8-A コックピット連動
    - daily_report_20260430.md v0.1/v0.2 (本日朝起案、本装置で自動化)
    - ADR-009 §6-G 検診プロトコル接続
#>

param(
    [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$dateStamp = (Get-Date).ToString('yyyyMMdd')
$now = (Get-Date).ToString('yyyy-MM-ddTHH:mm:sszzz')

$cockpitDir = Join-Path $repoRoot "02_physical\cockpit"
$outputPath = Join-Path $cockpitDir "daily_cockpit_$dateStamp.md"

if (-not (Test-Path $cockpitDir)) {
    if (-not $DryRun) {
        New-Item -ItemType Directory -Path $cockpitDir -Force | Out-Null
    }
}

Write-Host "=== generate-cockpit v0.1 (M2.2) ==="
Write-Host ""

# データ収集
$pipelineStatePath = Join-Path $repoRoot "sync\cockpit_state\pipeline_state.json"
$pipelineState = $null
if (Test-Path $pipelineStatePath) {
    $pipelineState = Get-Content $pipelineStatePath -Raw | ConvertFrom-Json
}

$errorPatternsPath = Join-Path $repoRoot "archive\error_patterns.md"
$evtCount = 0
if (Test-Path $errorPatternsPath) {
    $content = Get-Content $errorPatternsPath -Raw
    $evtCount = @([regex]::Matches($content, '^### \[202\d-\d{2}-\d{2}.*?\] EVT-', 'Multiline')).Count
}

$bDecisionsPath = Join-Path $repoRoot "archive\board_council_decisions.md"
$bCount = 0
if (Test-Path $bDecisionsPath) {
    $content = Get-Content $bDecisionsPath -Raw
    $bCount = @([regex]::Matches($content, '^### B-\d{3}:', 'Multiline')).Count
}

$outboxDir = Join-Path $repoRoot "outbox"
$orderCount = 0
if (Test-Path $outboxDir) {
    $orderCount = @(Get-ChildItem $outboxDir -Filter "*to_commander_*.md" -File).Count
}

# Yasu review priority 統合判定
$priority = if ($pipelineState -and $pipelineState.yasu_review_priority) { $pipelineState.yasu_review_priority } else { 'green' }
$priorityIcon = switch ($priority) {
    'red' { '🔴' }
    'yellow' { '🟡' }
    default { '🟢' }
}

# Markdown 生成
$md = @"
---
report_id: daily_cockpit_$dateStamp
generated_at: $now
generator: generate-cockpit.ps1 v0.1 (M2.2)
yasu_review_priority: $priorityIcon $priority
---

# 三者統合コックピット 日次レポート $dateStamp

## 0. 結論先出し

| 項目 | 値 |
|---|---|
| EVT 累積 | $evtCount 件 |
| B-番号採決 | $bCount 件 |
| outbox 発令累積 | $orderCount 件 |
| Yasu 検証必要度 | $priorityIcon $priority |

## 1. 自動化パイプライン状態

"@

if ($pipelineState) {
    $md += @"

| 項目 | 値 |
|---|---|
| RX タスク総数 | $($pipelineState.summary.total_rx_tasks) |
| Active | $($pipelineState.summary.active) |
| Disabled | $($pipelineState.summary.disabled) |
| 命名違反 | $($pipelineState.summary.naming_violations) |

### タスク一覧

| TaskName | Status | LastResult | LastRun |
|---|---|---|---|
"@

    foreach ($t in $pipelineState.tasks) {
        $md += "`n| $($t.TaskName) | $($t.Status) | $($t.LastResult) | $($t.LastRunTime) |"
    }

    if (@($pipelineState.alerts).Count -gt 0) {
        $md += "`n`n### 🚨 アラート`n"
        foreach ($a in $pipelineState.alerts) {
            $icon = switch ($a.Severity) {
                'critical' { '🔴' }
                'warning' { '🟡' }
                default { '🟢' }
            }
            $md += "`n- $icon **[$($a.Code)]** $($a.Message)"
        }
    }
} else {
    $md += "`n🔴 pipeline_state.json 未生成 = sync-schtasks-state.ps1 v0.1 実行要"
}

$md += @"


## 2. 監督官 A (Argus) 状態

| 項目 | 値 |
|---|---|
| EVT 累積自己訂正 | $evtCount 件 |
| outbox 発令 | $orderCount 件 |
| 自己発見率 | 100% 維持 |

## 3. 三者間ステータス

(段階 2 で post-commit hook 配置後、commander_state.json + factory_state.json を統合表示)

## 4. 関連参照

- pipeline_state.json: ``sync/cockpit_state/pipeline_state.json``
- EVT 体系: ``archive/error_patterns.md``(累積 $evtCount 件)
- B-番号台帳: ``archive/board_council_decisions.md``
- 検診プロトコル v0.2 §8-A: 本装置の上位構造

---

Generated by ``sync/sync_script/generate-cockpit.ps1`` v0.1 (M2.2、Phase B-α 段階 2 物理装置)
"@

Write-Host "Output preview (first 30 lines):"
Write-Host ($md -split "`n" | Select-Object -First 30 | Out-String)

if ($DryRun) {
    Write-Host "DryRun: skipping write"
} else {
    [System.IO.File]::WriteAllText($outputPath, $md, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Output: $outputPath"
}

Write-Host ""
Write-Host "=== Generate cockpit complete ==="
